### ISSUE TITLE
Could this library be updated to be compatible with uCam-III ?

### ISSUE THREAD

**Issue by q2dg** [dgtlmoon/uCamII#2]
Thanks a lot

**Comment by dgtlmoon** [comment]
RTFM

http://www.4dsystems.com.au/product/uCAM_III/

> The uCAM-III is a backwards-compatible upgrade to the uCAM-II
> 
> It can be used in places where the uCAM-II was used, but adds additional benefits such as:
> 
> Addition of Hardware Reset on 5-way header pin.
> Addition of 128KB of RAM on the camera to allow uCAM to handle more complex images rather than degrade picture quality.
> Addition of new commands exposure, contrast and brightness control, as well as adjustable sleep timeouts.
> Pullup Resistor on RX pin to prevent floating pin being mistaken as data.

**Comment by q2dg** [comment]
Ok, understood. 
But it would be worthy to modify **your** README accordingly.

**Comment by dgtlmoon** [comment]
@q2dg please supply a pull request
